theme: jekyll-theme-hacker
title: GitHub Pages 
チュードリアル
description: 自己紹介　安渡　翼
アップルパイが好きです。
<img src="tokyo0720IMGL7095_TP_V.jpg" alt="女" title="良いねえ"
width="200"height="200"/>                
github: 
  is_project_page: false
